// Mock data for UI development (Phase 1)
import type { Event, Space, Service } from '@/types/database';

export const mockEvents: Omit<Event, 'id' | 'created_at' | 'updated_at'>[] = [
  {
    title: 'Live Jazz Night im Glockenbach',
    description: 'Ein unvergesslicher Abend mit Live-Jazz, Cocktails und toller Atmosphäre',
    category: 'musik-performance',
    host_id: 'mock-user-1',
    location_address: 'Müllerstraße 12, 80469 München',
    location_lat: 48.1351,
    location_lng: 11.5820,
    start_time: '2025-10-15T20:00:00Z',
    end_time: '2025-10-15T23:00:00Z',
    price: 12,
    capacity: 30,
    image_urls: [],
  },
  {
    title: 'Yoga im Park - Morgenflow',
    description: 'Starte deinen Tag mit einer energiegeladenen Yoga-Session im Englischen Garten',
    category: 'sport-fitness',
    host_id: 'mock-user-2',
    location_address: 'Englischer Garten, 80538 München',
    location_lat: 48.1642,
    location_lng: 11.6056,
    start_time: '2025-10-12T08:00:00Z',
    end_time: '2025-10-12T09:30:00Z',
    price: 0,
    capacity: 20,
    image_urls: [],
  },
  {
    title: 'Kunstworkshop: Acrylmalerei',
    description: 'Lerne die Grundlagen der Acrylmalerei in entspannter Atmosphäre',
    category: 'kunst-kreativ',
    host_id: 'mock-user-3',
    location_address: 'Schwabing, 80799 München',
    location_lat: 48.1782,
    location_lng: 11.5775,
    start_time: '2025-10-18T14:00:00Z',
    end_time: '2025-10-18T17:00:00Z',
    price: 35,
    capacity: 12,
    image_urls: [],
  },
  {
    title: 'Familienpicknick im Westpark',
    description: 'Gemütliches Familienpicknick mit Spielen und Aktivitäten für Kinder',
    category: 'familie-kinder',
    host_id: 'mock-user-4',
    location_address: 'Westpark, 81373 München',
    location_lat: 48.1199,
    location_lng: 11.5265,
    start_time: '2025-10-20T11:00:00Z',
    end_time: '2025-10-20T15:00:00Z',
    price: 5,
    capacity: 50,
    image_urls: [],
  },
];

export const mockSpaces: Omit<Space, 'id' | 'created_at' | 'updated_at'>[] = [
  {
    title: 'Professionelles Tonstudio',
    description: 'Voll ausgestattetes Tonstudio mit modernster Recording-Technik',
    space_type: 'tonstudio',
    host_id: 'mock-user-5',
    location_address: 'Ludwigsvorstadt, 80336 München',
    location_lat: 48.1333,
    location_lng: 11.5594,
    hourly_rate: 45,
    daily_rate: 280,
    weekly_rate: 1500,
    size_sqm: 35,
    capacity: 5,
    amenities: ['Profi-Equipment', 'Klimaanlage', 'Küche', 'WiFi'],
    image_urls: [],
  },
  {
    title: 'Lichtdurchflutetes Fotostudio',
    description: 'Großes Studio mit natürlichem Licht und Profil-Ausstattung',
    space_type: 'fotostudio',
    host_id: 'mock-user-6',
    location_address: 'Maxvorstadt, 80333 München',
    location_lat: 48.1486,
    location_lng: 11.5728,
    hourly_rate: 35,
    daily_rate: 220,
    weekly_rate: 1200,
    size_sqm: 60,
    capacity: 8,
    amenities: ['Natürliches Licht', 'Backdrop', 'Umkleide', 'Parkplatz'],
    image_urls: [],
  },
  {
    title: 'Kreative Werkstatt',
    description: 'Werkstatt mit Holz- und Metallbearbeitung für DIY-Projekte',
    space_type: 'werkstaetten',
    host_id: 'mock-user-7',
    location_address: 'Haidhausen, 81667 München',
    location_lat: 48.1299,
    location_lng: 11.6037,
    hourly_rate: 25,
    daily_rate: 150,
    weekly_rate: 800,
    size_sqm: 80,
    capacity: 10,
    amenities: ['Werkzeuge', 'Arbeitsplätze', 'Lagerraum', 'WiFi'],
    image_urls: [],
  },
  {
    title: 'Popup Retail Space',
    description: 'Moderner Pop-up Store in bester Innenstadtlage',
    space_type: 'popup-retail',
    host_id: 'mock-user-8',
    location_address: 'Altstadt, 80331 München',
    location_lat: 48.1374,
    location_lng: 11.5755,
    hourly_rate: 60,
    daily_rate: 400,
    weekly_rate: 2200,
    size_sqm: 45,
    capacity: 20,
    amenities: ['Schaufenster', 'Lagerraum', 'Kassensystem', 'WiFi'],
    image_urls: [],
  },
];

export const mockServices: Omit<Service, 'id' | 'created_at' | 'updated_at'>[] = [
  {
    title: 'Professionelle Fotografie',
    description: 'Event-, Porträt- und Hochzeitsfotografie mit Erfahrung',
    category: 'fotografie',
    provider_id: 'mock-user-9',
    image_urls: [],
  },
  {
    title: 'Personal Training',
    description: 'Individuelles Fitness-Training für alle Level',
    category: 'sport',
    provider_id: 'mock-user-10',
    image_urls: [],
  },
  {
    title: 'DJ & Musikproduktion',
    description: 'Professioneller DJ-Service und Musikproduktion',
    category: 'musik',
    provider_id: 'mock-user-11',
    image_urls: [],
  },
];
